### ISSUE TITLE
Counting and the new version

### ISSUE THREAD

**Issue by Shifterovich** [aqos156/Pocitani-prumeru-znamek-bakalari#2]
Some values are incorrect, and generally the script is now *useless due to the NEXT version* (znamky.zsunesco.cz/next/login.aspx) which has these values now (and **correct**).

**The counting part requires debugging.**

**Comment by aqos156** [comment]
Yes, I know :D

**Comment by Shifterovich** [comment]
'Cause GitHub issues are cooler than Facebook chat.

**Comment by Shifterovich** [comment]
Říkal jsi, že to už funguje :D

**Comment by aqos156** [comment]
:D Hej zatím to fungovalo
